version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pesan-pms
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - BETTER_AUTH_SECRET=${BETTER_AUTH_SECRET:-s3cr3t}
      - BETTER_AUTH_URL=${BETTER_AUTH_URL:-http://localhost:3000}
      - NEXT_PUBLIC_BASE_URL=${NEXT_PUBLIC_BASE_URL:-http://localhost:3000}
      - NEXT_PUBLIC_PASSKEY_RP_ID=${NEXT_PUBLIC_PASSKEY_RP_ID:-localhost}
      - NEXT_PUBLIC_PASSKEY_ORIGIN=${NEXT_PUBLIC_PASSKEY_ORIGIN:-http://localhost:3000}
    volumes:
      - ./data:/app/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
